insert into can_conduct (lab_name, type_id) values ('Heel Inc', '50114-1064');
insert into can_conduct (lab_name, type_id) values ('Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.', '58232-0025');
insert into can_conduct (lab_name, type_id) values ('Sun & Skin Care Research, LLC', '62802-108');
insert into can_conduct (lab_name, type_id) values ('Colgate-Palmolive Company', '35000-879');
insert into can_conduct (lab_name, type_id) values ('AAA Pharmaceutical, Inc.', '57344-090');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-5525');
insert into can_conduct (lab_name, type_id) values ('Jubilant HollisterStier LLC', '65044-4352');
insert into can_conduct (lab_name, type_id) values ('Ferring Pharmaceuticals Inc.', '55566-8403');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0367');
insert into can_conduct (lab_name, type_id) values ('Merle Norman Cosmetics, Inc', '57627-133');
insert into can_conduct (lab_name, type_id) values ('Walgreens', '0363-1303');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-7540');
insert into can_conduct (lab_name, type_id) values ('Kmart Corporation', '49738-668');
insert into can_conduct (lab_name, type_id) values ('American Sales Company', '41520-323');
insert into can_conduct (lab_name, type_id) values ('Royal Pharmaceuticals', '68791-101');
insert into can_conduct (lab_name, type_id) values ('Blenheim Pharmacal, Inc.', '10544-095');
insert into can_conduct (lab_name, type_id) values ('STAT Rx USA LLC', '42549-589');
insert into can_conduct (lab_name, type_id) values ('Family Dollar', '55319-608');
insert into can_conduct (lab_name, type_id) values ('Teva Parenteral Medicines, Inc.', '0703-9032');
insert into can_conduct (lab_name, type_id) values ('DeMoulas Market Basket', '53942-504');
insert into can_conduct (lab_name, type_id) values ('North Central Medical Supply, Inc.', '45028-001');
insert into can_conduct (lab_name, type_id) values ('Techgas Inc.', '64069-4111');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-0691');
insert into can_conduct (lab_name, type_id) values ('Rise International Group LLC', '67143-0101');
insert into can_conduct (lab_name, type_id) values ('Sagent Pharmaceuticals', '25021-651');
insert into can_conduct (lab_name, type_id) values ('BioActive Nutritional, Inc.', '43857-0177');
insert into can_conduct (lab_name, type_id) values ('Matrixx Initiatives, Inc.', '62750-031');
insert into can_conduct (lab_name, type_id) values ('Akorn, Inc.', '17478-190');
insert into can_conduct (lab_name, type_id) values ('Uriel Pharmacy Inc.', '48951-1107');
insert into can_conduct (lab_name, type_id) values ('CorePharma, LLC', '64720-128');
insert into can_conduct (lab_name, type_id) values ('Contract Pharmacy Services-PA', '67046-163');
insert into can_conduct (lab_name, type_id) values ('Bracco Diagnostics Inc', '0270-1315');
insert into can_conduct (lab_name, type_id) values ('Valeant Pharmaceuticals North America LLC', '0187-0192');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical DBA Quality Care Products LLC', '35356-169');
insert into can_conduct (lab_name, type_id) values ('Newton Laboratories, Inc.', '55714-4537');
insert into can_conduct (lab_name, type_id) values ('B. Braun Medical Inc.', '0264-9872');
insert into can_conduct (lab_name, type_id) values ('CLINIQUE LABORATORIES INC', '49527-825');
insert into can_conduct (lab_name, type_id) values ('McKesson', '49348-135');
insert into can_conduct (lab_name, type_id) values ('Eight and Company', '61096-0031');
insert into can_conduct (lab_name, type_id) values ('Topco Associates LLC', '36800-922');
insert into can_conduct (lab_name, type_id) values ('AbbVie Inc.', '0074-3799');
insert into can_conduct (lab_name, type_id) values ('Bare Escentuals Beauty, Inc.', '98132-704');
insert into can_conduct (lab_name, type_id) values ('Rugby Laboratories, Inc.', '0536-2220');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-5260');
insert into can_conduct (lab_name, type_id) values ('PD-Rx Pharmaceuticals, Inc.', '43063-407');
insert into can_conduct (lab_name, type_id) values ('AMI Cosmetic Co.,Ltd.', '59535-9901');
insert into can_conduct (lab_name, type_id) values ('Kmart Corporation', '49738-424');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0363');
insert into can_conduct (lab_name, type_id) values ('Unit Dose Services', '50436-6613');
insert into can_conduct (lab_name, type_id) values ('STI Pharma', '68850-004');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-6646');
insert into can_conduct (lab_name, type_id) values ('PD-Rx Pharmaceuticals, Inc.', '55289-022');
insert into can_conduct (lab_name, type_id) values ('Family Dollar', '55319-534');
insert into can_conduct (lab_name, type_id) values ('GANZ U.S.A., LLC', '75862-009');
insert into can_conduct (lab_name, type_id) values ('Publix Super Markets Inc', '56062-255');
insert into can_conduct (lab_name, type_id) values ('Qualitest Pharmaceuticals', '0603-7525');
insert into can_conduct (lab_name, type_id) values ('GlaxoSmithKline Consumer Healthcare LP', '0135-0199');
insert into can_conduct (lab_name, type_id) values ('The Wellness Center', '50181-0001');
insert into can_conduct (lab_name, type_id) values ('Paddock Laboratories, LLC', '0574-9838');
insert into can_conduct (lab_name, type_id) values ('AvPAK', '50268-305');
insert into can_conduct (lab_name, type_id) values ('Publix Super Markets Inc', '56062-462');
insert into can_conduct (lab_name, type_id) values ('Wal-Mart Stores Inc', '49035-998');
insert into can_conduct (lab_name, type_id) values ('PD-Rx Pharmaceuticals, Inc.', '43063-422');
insert into can_conduct (lab_name, type_id) values ('BluePoint Laboratories', '68001-163');
insert into can_conduct (lab_name, type_id) values ('Genentech, Inc.', '0004-0365');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-3343');
insert into can_conduct (lab_name, type_id) values ('Epic Pharma, LLC', '42806-058');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-4837');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-3070');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-1259');
insert into can_conduct (lab_name, type_id) values ('CHANEL PARFUMS BEAUTE', '68745-1051');
insert into can_conduct (lab_name, type_id) values ('Valu Merchandisers Company', '63941-333');
insert into can_conduct (lab_name, type_id) values ('Upsher-Smith Laboratories, Inc.', '0245-0872');
insert into can_conduct (lab_name, type_id) values ('Asclemed USA, Inc.', '76420-750');
insert into can_conduct (lab_name, type_id) values ('Aero All Gas Company', '10014-001');
insert into can_conduct (lab_name, type_id) values ('Chattem, Inc.', '41167-0172');
insert into can_conduct (lab_name, type_id) values ('Valeant Pharmaceuticals North America LLC', '0187-1619');
insert into can_conduct (lab_name, type_id) values ('Fresenius Kabi USA, LLC', '63323-379');
insert into can_conduct (lab_name, type_id) values ('Roxane Laboratories, Inc', '0054-3176');
insert into can_conduct (lab_name, type_id) values ('Meijer Distribution Inc', '41250-017');
insert into can_conduct (lab_name, type_id) values ('Janssen Pharmaceuticals, Inc.', '50458-586');
insert into can_conduct (lab_name, type_id) values ('Vertical Pharmaceuticals, Inc.', '68025-058');
insert into can_conduct (lab_name, type_id) values ('Fresenius Kabi USA, LLC', '63323-317');
insert into can_conduct (lab_name, type_id) values ('SUPERVALU INC.', '41163-373');
insert into can_conduct (lab_name, type_id) values ('AMERICAN SALES', '41520-343');
insert into can_conduct (lab_name, type_id) values ('ALDI INC', '64024-970');
insert into can_conduct (lab_name, type_id) values ('New World Imports, Inc', '51824-035');
insert into can_conduct (lab_name, type_id) values ('Legacy Pharmaceutical Packaging', '68645-488');
insert into can_conduct (lab_name, type_id) values ('Biometics Co.,Ltd.', '62818-100');
insert into can_conduct (lab_name, type_id) values ('GlaxoSmithKline LLC', '0173-0845');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-2063');
insert into can_conduct (lab_name, type_id) values ('F&CO Co., Ltd.', '69106-060');
insert into can_conduct (lab_name, type_id) values ('Safeway', '21130-373');
insert into can_conduct (lab_name, type_id) values ('Faria LLC dba Sheffield Pharmaceuticals', '11527-052');
insert into can_conduct (lab_name, type_id) values ('OraLabs', '63645-140');
insert into can_conduct (lab_name, type_id) values ('Natural Health Supply', '64117-250');
insert into can_conduct (lab_name, type_id) values ('Fresenius Kabi USA, LLC', '63323-013');
insert into can_conduct (lab_name, type_id) values ('Ecolab Inc.', '47593-501');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', '35356-982');
insert into can_conduct (lab_name, type_id) values ('Kingsbridge International, Inc.', '69124-002');
insert into can_conduct (lab_name, type_id) values ('Pure Source, Inc.', '65121-562');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1412');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-7167');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-5375');
insert into can_conduct (lab_name, type_id) values ('GlaxoSmithKline Consumer Healthcare LP', '0135-0432');
insert into can_conduct (lab_name, type_id) values ('Allermed Laboratories, Inc.', '49643-448');
insert into can_conduct (lab_name, type_id) values ('WOONSOCKET PRESCRIPTION CENTER,INCORPORATED', '59779-863');
insert into can_conduct (lab_name, type_id) values ('NARTEX LABORATORIOS HOMEOPATICOS SA DE CV', '34666-111');
insert into can_conduct (lab_name, type_id) values ('International Nature Nutraceuticals', '51367-021');
insert into can_conduct (lab_name, type_id) values ('Parke-Davis Div of Pfizer Inc', '0071-0401');
insert into can_conduct (lab_name, type_id) values ('Laura Geller Beauty, LLC', '51389-203');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-1512');
insert into can_conduct (lab_name, type_id) values ('Cypress Pharmaceutical, Inc.', '60258-158');
insert into can_conduct (lab_name, type_id) values ('L''Oreal USA Products Inc', '49967-166');
insert into can_conduct (lab_name, type_id) values ('Stratus Pharmaceuticals', '58980-415');
insert into can_conduct (lab_name, type_id) values ('Valeant Pharmaceuticals North America LLC', '0187-0063');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-607');
insert into can_conduct (lab_name, type_id) values ('Hospira, Inc.', '0409-6179');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-5683');
insert into can_conduct (lab_name, type_id) values ('Ventura Corporation Ltd', '13537-148');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-6920');
insert into can_conduct (lab_name, type_id) values ('Major Pharmaceuticals', '0904-5990');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-3269');
insert into can_conduct (lab_name, type_id) values ('Dr.Reddy''s Laboratories Limited', '55111-272');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-1332');
insert into can_conduct (lab_name, type_id) values ('GEISS, DESTIN AND DUNN, INC.', '75981-001');
insert into can_conduct (lab_name, type_id) values ('Aurolife Pharma LLC', '13107-054');
insert into can_conduct (lab_name, type_id) values ('Medtech Products Inc.', '63029-505');
insert into can_conduct (lab_name, type_id) values ('KAISER FOUNDATION HOSPITALS', '0179-0020');
insert into can_conduct (lab_name, type_id) values ('Geiss, Destin & Dunn, Inc', '50804-871');
insert into can_conduct (lab_name, type_id) values ('COSTCO WHOLESALE CORPORATION', '63981-329');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2402');
insert into can_conduct (lab_name, type_id) values ('STAT RX USA LLC', '16590-171');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-259');
insert into can_conduct (lab_name, type_id) values ('Actavis Elizabeth LLC', '0228-2980');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-4532');
insert into can_conduct (lab_name, type_id) values ('Syntrion GmbH', '10424-148');
insert into can_conduct (lab_name, type_id) values ('LABORATORIOS DE COSMETICA SCIENTIFICA ATACHE SA', '75870-001');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-1040');
insert into can_conduct (lab_name, type_id) values ('Kareway Product, Inc.', '67510-0667');
insert into can_conduct (lab_name, type_id) values ('Hawthorn Pharmaceuticals, Inc.', '63717-901');
insert into can_conduct (lab_name, type_id) values ('J. A. Cosmetics U.S. INC', '76354-016');
insert into can_conduct (lab_name, type_id) values ('Vitality Works, Inc.', '64616-092');
insert into can_conduct (lab_name, type_id) values ('PD-Rx Pharmaceuticals, Inc.', '68752-025');
insert into can_conduct (lab_name, type_id) values ('Hannaford Brothers Company', '41268-484');
insert into can_conduct (lab_name, type_id) values ('Pharmaceutical Associates, Inc.', '0121-4675');
insert into can_conduct (lab_name, type_id) values ('Sanum Kehlbeck GmbH & Co. KG', '60681-1403');
insert into can_conduct (lab_name, type_id) values ('Barr Laboratories Inc.', '0555-0955');
insert into can_conduct (lab_name, type_id) values ('International Cosmetic Limited', '66969-6012');
insert into can_conduct (lab_name, type_id) values ('ORIGINS NATURAL RESOURCES INC', '59427-728');
insert into can_conduct (lab_name, type_id) values ('Aidarex Pharmaceuticals LLC', '33261-035');
insert into can_conduct (lab_name, type_id) values ('WEIMEI Lianyungang Household Articles Manufacturing Co. LTD', '50827-003');
insert into can_conduct (lab_name, type_id) values ('AAA Pharmaceutical, Inc.', '57344-158');
insert into can_conduct (lab_name, type_id) values ('Mission Pharmacal Company', '0178-0370');
insert into can_conduct (lab_name, type_id) values ('Mission Hills, S.A. de C.V.', '65954-063');
insert into can_conduct (lab_name, type_id) values ('Rebel Distributors Corp', '21695-589');
insert into can_conduct (lab_name, type_id) values ('Have and Be Co., Ltd.', '49404-113');
insert into can_conduct (lab_name, type_id) values ('Allergan, Inc.', '0023-8842');
insert into can_conduct (lab_name, type_id) values ('GlaxoSmithKline LLC', '0173-0561');
insert into can_conduct (lab_name, type_id) values ('Panrosa Enterprises, Inc.', '50302-400');
insert into can_conduct (lab_name, type_id) values ('Seton Pharmaceuticals', '13925-169');
insert into can_conduct (lab_name, type_id) values ('WALGREEN COMPANY', '0363-0147');
insert into can_conduct (lab_name, type_id) values ('Bryant Ranch Prepack', '63629-1318');
insert into can_conduct (lab_name, type_id) values ('Fresenius Kabi USA, LLC', '63323-285');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-424');
insert into can_conduct (lab_name, type_id) values ('Forces of Nature', '51393-6669');
insert into can_conduct (lab_name, type_id) values ('NCS HealthCare of KY, Inc dba Vangard Labs', '0615-7679');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-061');
insert into can_conduct (lab_name, type_id) values ('BioActive Nutritional, Inc.', '43857-0304');
insert into can_conduct (lab_name, type_id) values ('Taro Pharmaceuticals U.S.A., Inc.', '51672-2097');
insert into can_conduct (lab_name, type_id) values ('American Health Packaging', '68084-098');
insert into can_conduct (lab_name, type_id) values ('International Labs, Inc.', '54458-945');
insert into can_conduct (lab_name, type_id) values ('Chain Drug Marketing Association', '63868-156');
insert into can_conduct (lab_name, type_id) values ('L. Perrigo Company', '0113-0368');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-1400');
insert into can_conduct (lab_name, type_id) values ('SHISEIDO CO., LTD.', '52685-432');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-5016');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0790');
insert into can_conduct (lab_name, type_id) values ('Chain Drug Consortium', '68016-952');
insert into can_conduct (lab_name, type_id) values ('Washington Homeopathic Products', '68428-027');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-629');
insert into can_conduct (lab_name, type_id) values ('U.S. Pharmaceuticals', '63539-021');
insert into can_conduct (lab_name, type_id) values ('Kinray Inc.', '63777-214');
insert into can_conduct (lab_name, type_id) values ('ABCO Welding and Industrial Supply Inc', '54949-004');
insert into can_conduct (lab_name, type_id) values ('Jets, Sets, & Elephants Beauty Corp.', '50988-298');
insert into can_conduct (lab_name, type_id) values ('Newton Laboratories, Inc.', '55714-1118');
insert into can_conduct (lab_name, type_id) values ('Caraco Pharmaceutical Laboratories, Ltd.', '57664-146');
insert into can_conduct (lab_name, type_id) values ('Avion Pharmaceuticals, LLC', '75854-202');
insert into can_conduct (lab_name, type_id) values ('McKesson Packaging Services Business Unit of McKesson Corporation', '63739-470');
insert into can_conduct (lab_name, type_id) values ('NDC National Distribution & Contracting, Inc.', '43128-108');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1262');
insert into can_conduct (lab_name, type_id) values ('King Bio Inc.', '57955-1021');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical DBA Quality Care Products LLC', '49999-817');
insert into can_conduct (lab_name, type_id) values ('Clinical Solutions Wholesale', '58118-0114');
insert into can_conduct (lab_name, type_id) values ('STAT Rx USA LLC', '16590-058');
insert into can_conduct (lab_name, type_id) values ('Sun Pharma Global FZE', '47335-937');
insert into can_conduct (lab_name, type_id) values ('Dukal Corporation', '65517-1002');
insert into can_conduct (lab_name, type_id) values ('Uriel Pharmacy Inc.', '48951-1098');
insert into can_conduct (lab_name, type_id) values ('General Injectables and Vaccines, Inc.', '52584-060');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-3109');
insert into can_conduct (lab_name, type_id) values ('International Labs, Inc.', '54458-967');
insert into can_conduct (lab_name, type_id) values ('Actavis Elizabeth LLC', '0228-2899');
insert into can_conduct (lab_name, type_id) values ('MallyGirl, LLC', '76119-1444');
insert into can_conduct (lab_name, type_id) values ('Guna spa', '17089-294');
insert into can_conduct (lab_name, type_id) values ('Wal-Mart Stores Inc.', '49035-212');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-5335');
insert into can_conduct (lab_name, type_id) values ('Topco Associates LLC', '36800-133');
insert into can_conduct (lab_name, type_id) values ('General Injectables & Vaccines, Inc', '52584-018');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-120');
insert into can_conduct (lab_name, type_id) values ('Aurobindo Pharma Limited', '65862-503');
insert into can_conduct (lab_name, type_id) values ('KAISER FOUNDATION HOSPITALS', '0179-0059');
insert into can_conduct (lab_name, type_id) values ('Omega Industrial Supply, Inc.', '68642-783');
insert into can_conduct (lab_name, type_id) values ('McKesson', '49348-266');
insert into can_conduct (lab_name, type_id) values ('HOMEOLAB USA INC.', '60512-6350');
insert into can_conduct (lab_name, type_id) values ('King Bio Inc.', '57955-2282');
insert into can_conduct (lab_name, type_id) values ('LG Household and Healthcare, Inc.', '53208-520');
insert into can_conduct (lab_name, type_id) values ('Mallinckrodt Inc.', '0019-9601');
insert into can_conduct (lab_name, type_id) values ('Sandoz Inc', '0781-3139');
insert into can_conduct (lab_name, type_id) values ('Ferndale Laboratories, Inc.', '0496-0750');
insert into can_conduct (lab_name, type_id) values ('McKesson Contract Packager', '76237-299');
insert into can_conduct (lab_name, type_id) values ('St Marys Medical Park Pharmacy', '60760-124');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-0137');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0731');
insert into can_conduct (lab_name, type_id) values ('Grahams Natural Alternatives Pty Ltd', '42387-123');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2632');
insert into can_conduct (lab_name, type_id) values ('American Sales Company', '41520-878');
insert into can_conduct (lab_name, type_id) values ('PD-Rx Pharmaceuticals, Inc.', '43063-225');
insert into can_conduct (lab_name, type_id) values ('Bare Escentuals Beauty Inc.', '98132-893');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-4221');
insert into can_conduct (lab_name, type_id) values ('WOCKHARDT LIMITED', '55648-412');
insert into can_conduct (lab_name, type_id) values ('Falcon Pharmaceuticals, Ltd.', '61314-206');
insert into can_conduct (lab_name, type_id) values ('APP Pharmaceuticals, LLC', '63323-113');
insert into can_conduct (lab_name, type_id) values ('Amneal Pharmaceuticals of New York, LLC', '65162-305');
insert into can_conduct (lab_name, type_id) values ('STAT RX USA LLC', '16590-594');
insert into can_conduct (lab_name, type_id) values ('L''Oreal USA Products Inc', '49967-644');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-501');
insert into can_conduct (lab_name, type_id) values ('Select Brand', '15127-979');
insert into can_conduct (lab_name, type_id) values ('MSD Consumer Care, Inc.', '11523-7338');
insert into can_conduct (lab_name, type_id) values ('Western Family Foods Inc', '55312-829');
insert into can_conduct (lab_name, type_id) values ('AvPAK', '50268-517');
insert into can_conduct (lab_name, type_id) values ('Hawthorn Pharmaceuticals, Inc.', '63717-326');
insert into can_conduct (lab_name, type_id) values ('Novo Nordisk', '0169-7040');
insert into can_conduct (lab_name, type_id) values ('American Antibiotics, Inc', '15749-801');
insert into can_conduct (lab_name, type_id) values ('Dispensing Solutions, Inc.', '68258-8987');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2456');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical DBA Quality Care Products LLC', '49999-846');
insert into can_conduct (lab_name, type_id) values ('H E B', '37808-396');
insert into can_conduct (lab_name, type_id) values ('Ranbaxy Pharmaceuticals Inc', '63304-436');
insert into can_conduct (lab_name, type_id) values ('PUREMEDY', '52810-501');
insert into can_conduct (lab_name, type_id) values ('Forces of Nature', '51393-6666');
insert into can_conduct (lab_name, type_id) values ('A-S Medication Solutions LLC', '54569-3820');
insert into can_conduct (lab_name, type_id) values ('SAFEWAY INC.', '21130-416');
insert into can_conduct (lab_name, type_id) values ('A-S Medication Solutions LLC', '54569-1712');
insert into can_conduct (lab_name, type_id) values ('Woodbine Products Company', '11429-1001');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-6360');
insert into can_conduct (lab_name, type_id) values ('Preferred Pharmaceuticals, Inc', '68788-0134');
insert into can_conduct (lab_name, type_id) values ('Aton Pharma, Inc.', '25010-805');
insert into can_conduct (lab_name, type_id) values ('Genentech, Inc.', '50242-138');
insert into can_conduct (lab_name, type_id) values ('McKesson Packaging Services Business Unit of McKesson Corporation', '63739-452');
insert into can_conduct (lab_name, type_id) values ('Aurobindo Pharma Limited', '65862-565');
insert into can_conduct (lab_name, type_id) values ('Dr. Reddy''s Laboratories Inc', '43598-018');
insert into can_conduct (lab_name, type_id) values ('Indiana Botanic Gardens', '10578-042');
insert into can_conduct (lab_name, type_id) values ('Pharmacia and Upjohn Company', '0009-0003');
insert into can_conduct (lab_name, type_id) values ('Safeway', '21130-391');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-0536');
insert into can_conduct (lab_name, type_id) values ('Linde LLC', '52438-011');
insert into can_conduct (lab_name, type_id) values ('A-S Medication Solutions LLC', '54569-3755');
insert into can_conduct (lab_name, type_id) values ('Allergy Laboratories, Inc.', '54575-949');
insert into can_conduct (lab_name, type_id) values ('Akorn, Inc.', '17478-763');
insert into can_conduct (lab_name, type_id) values ('Proficient Rx LP', '63187-104');
insert into can_conduct (lab_name, type_id) values ('Neutrogena Corporation', '10812-528');
insert into can_conduct (lab_name, type_id) values ('Advantage Sales and Marketing', '68858-100');
insert into can_conduct (lab_name, type_id) values ('Kara Vita, Inc.', '68572-4014');
insert into can_conduct (lab_name, type_id) values ('Rimmel Inc.', '76485-1021');
insert into can_conduct (lab_name, type_id) values ('UDL Laboratories, Inc.', '51079-938');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical DBA Quality Care Products LLC', '35356-939');
insert into can_conduct (lab_name, type_id) values ('MSD Consumer Care, Inc.', '11523-7363');
insert into can_conduct (lab_name, type_id) values ('Clinical Solutions Wholesale', '58118-1391');
insert into can_conduct (lab_name, type_id) values ('Summers Laboratories Inc', '11086-030');
insert into can_conduct (lab_name, type_id) values ('Hospira, Inc.', '0409-0217');
insert into can_conduct (lab_name, type_id) values ('Bolero Home Decor, Inc.', '57469-053');
insert into can_conduct (lab_name, type_id) values ('Unit Dose Services', '50436-3988');
insert into can_conduct (lab_name, type_id) values ('Aidarex Pharmaceuticals LLC', '33261-137');
insert into can_conduct (lab_name, type_id) values ('Legacy Pharmaceutical Packaging', '68645-425');
insert into can_conduct (lab_name, type_id) values ('The Mentholatum Company', '10742-8271');
insert into can_conduct (lab_name, type_id) values ('Aphena Pharma Solutions - Tennessee, LLC', '43353-689');
insert into can_conduct (lab_name, type_id) values ('TYA Pharmaceuticals', '64725-0146');
insert into can_conduct (lab_name, type_id) values ('BB17, LLC', '53603-1007');
insert into can_conduct (lab_name, type_id) values ('Glenmark Generics Inc., USA', '68462-556');
insert into can_conduct (lab_name, type_id) values ('Wockhardt Limited', '55648-632');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-640');
insert into can_conduct (lab_name, type_id) values ('Family Dollar', '55319-619');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-122');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-299');
insert into can_conduct (lab_name, type_id) values ('L.N.K. International, Inc.', '50844-529');
insert into can_conduct (lab_name, type_id) values ('7-Eleven', '10202-458');
insert into can_conduct (lab_name, type_id) values ('NATURE REPUBLIC CO., LTD.', '51346-204');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0067');
insert into can_conduct (lab_name, type_id) values ('Wyeth Pharmaceutical Division of Wyeth Holdings Corporation, a subsidiary of Pfizer Inc.', '0005-1970');
insert into can_conduct (lab_name, type_id) values ('Marco Pharma International LLC.', '60986-1011');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-751');
insert into can_conduct (lab_name, type_id) values ('AvKARE, Inc.', '42291-113');
insert into can_conduct (lab_name, type_id) values ('HOMEOLAB USA INC.', '60512-6545');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-0622');
insert into can_conduct (lab_name, type_id) values ('NATURE REPUBLIC CO., LTD.', '51346-205');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-1339');
insert into can_conduct (lab_name, type_id) values ('Solazyme, Inc.', '53407-155');
insert into can_conduct (lab_name, type_id) values ('Jubilant HollisterStier LLC', '65044-6517');
insert into can_conduct (lab_name, type_id) values ('Smart and Final Stores', '59860-519');
insert into can_conduct (lab_name, type_id) values ('Delta Brands Inc', '20276-162');
insert into can_conduct (lab_name, type_id) values ('Gadal Laboratories Inc', '53113-105');
insert into can_conduct (lab_name, type_id) values ('Linde Gas North America LLC', '25373-012');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1403');
insert into can_conduct (lab_name, type_id) values ('Genuine First Aid LLC', '52124-0012');
insert into can_conduct (lab_name, type_id) values ('American Health Packaging', '68084-537');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-873');
insert into can_conduct (lab_name, type_id) values ('Wildlife Research Center, Inc.', '64776-696');
insert into can_conduct (lab_name, type_id) values ('Baxter Healthcare Corporation', '0338-0550');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-6143');
insert into can_conduct (lab_name, type_id) values ('Merz Pharmaceuticals, LLC', '0259-3192');
insert into can_conduct (lab_name, type_id) values ('Aphena Pharma Solutions - Tennessee, LLC', '43353-796');
insert into can_conduct (lab_name, type_id) values ('Hospira, Inc.', '0409-6509');
insert into can_conduct (lab_name, type_id) values ('Sandoz Inc', '0781-9404');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-7299');
insert into can_conduct (lab_name, type_id) values ('Shopko Stores Operating Co., LLC', '37012-304');
insert into can_conduct (lab_name, type_id) values ('Carib Sales, LLC', '60927-117');
insert into can_conduct (lab_name, type_id) values ('Newton Laboratories, Inc.', '55714-4503');
insert into can_conduct (lab_name, type_id) values ('Bonne Bell LLC', '50051-0005');
insert into can_conduct (lab_name, type_id) values ('Allergy Laboratories, Inc.', '54575-958');
insert into can_conduct (lab_name, type_id) values ('State of Florida DOH Central Pharmacy', '53808-0906');
insert into can_conduct (lab_name, type_id) values ('Hospira, Inc.', '0409-7925');
insert into can_conduct (lab_name, type_id) values ('Advanced Vision Research (Subsidiary of Akorn, Inc.)', '58790-002');
insert into can_conduct (lab_name, type_id) values ('Prasco Laboratories', '66993-410');
insert into can_conduct (lab_name, type_id) values ('Aidance Skincare & Topical Solutions, LLC', '24909-148');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-265');
insert into can_conduct (lab_name, type_id) values ('H.J. Harkins Company, Inc.', '52959-652');
insert into can_conduct (lab_name, type_id) values ('Elizabeth Arden, Inc', '67938-1154');
insert into can_conduct (lab_name, type_id) values ('E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.', '0168-0062');
insert into can_conduct (lab_name, type_id) values ('Procter & Gamble Manufacturing Co.', '37000-072');
insert into can_conduct (lab_name, type_id) values ('Major Pharmaceuticals', '0904-2667');
insert into can_conduct (lab_name, type_id) values ('Z.H.T. ENGINEERING EQUIPMENT AND TECHNOLOGIES LTD', '54095-111');
insert into can_conduct (lab_name, type_id) values ('Ventura International LTD.', '14783-330');
insert into can_conduct (lab_name, type_id) values ('State of Florida DOH Central Pharmacy', '53808-0693');
insert into can_conduct (lab_name, type_id) values ('Taizhou Xinzhixuan Daily-Use Co., Ltd.', '50593-008');
insert into can_conduct (lab_name, type_id) values ('Parfums Christian Dior', '61957-1310');
insert into can_conduct (lab_name, type_id) values ('Uriel Pharmacy Inc.', '48951-1161');
insert into can_conduct (lab_name, type_id) values ('Homeopath Ellen''s', '59985-101');
insert into can_conduct (lab_name, type_id) values ('Kosan Kozmetik Sanayi ve Ticaret A.S.', '61722-061');
insert into can_conduct (lab_name, type_id) values ('Major Pharmaceuticals', '0904-5991');
insert into can_conduct (lab_name, type_id) values ('Jubilant HollisterStier LLC', '65044-2486');
insert into can_conduct (lab_name, type_id) values ('bryant ranch prepack', '63629-2958');
insert into can_conduct (lab_name, type_id) values ('Barr Laboratories Inc.', '0555-0606');
insert into can_conduct (lab_name, type_id) values ('McKesson', '49348-957');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-636');
insert into can_conduct (lab_name, type_id) values ('Trinity Pharmaceuticals, LLC', '54295-301');
insert into can_conduct (lab_name, type_id) values ('Preferred Pharmaceuticals, Inc.', '68788-0985');
insert into can_conduct (lab_name, type_id) values ('Sandoz Inc', '0781-5192');
insert into can_conduct (lab_name, type_id) values ('Preferred Pharmaceuticals, Inc.', '68788-9669');
insert into can_conduct (lab_name, type_id) values ('Allermed Laboratories, Inc.', '49643-351');
insert into can_conduct (lab_name, type_id) values ('Schering Plough HealthCare Products', '11523-0728');
insert into can_conduct (lab_name, type_id) values ('Newton Laboratories, Inc.', '55714-4542');
insert into can_conduct (lab_name, type_id) values ('McKesson Contract Packaging', '76237-126');
insert into can_conduct (lab_name, type_id) values ('Excella GmbH', '46014-0501');
insert into can_conduct (lab_name, type_id) values ('Ventura Corporation LTD.', '13537-032');
insert into can_conduct (lab_name, type_id) values ('Fresh, Inc.', '42406-100');
insert into can_conduct (lab_name, type_id) values ('Paddock Laboratories, LLC', '0574-2004');
insert into can_conduct (lab_name, type_id) values ('Dukal Corporation', '65517-0027');
insert into can_conduct (lab_name, type_id) values ('Par Pharmaceutical Inc.', '49884-664');
insert into can_conduct (lab_name, type_id) values ('HOMEOLAB USA INC.', '60512-6009');
insert into can_conduct (lab_name, type_id) values ('Family Dollar', '55319-626');
insert into can_conduct (lab_name, type_id) values ('Aurobindo Pharma Limited', '65862-117');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-6533');
insert into can_conduct (lab_name, type_id) values ('Golden State Medical Supply, Inc.', '60429-281');
insert into can_conduct (lab_name, type_id) values ('Caraco Pharmaceutical Laboratories, Ltd.', '57664-175');
insert into can_conduct (lab_name, type_id) values ('Meijer Distribution Inc', '41250-377');
insert into can_conduct (lab_name, type_id) values ('Perrigo New York Inc', '45802-770');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-6279');
insert into can_conduct (lab_name, type_id) values ('Sun Pharmaceutical Industries Limited', '62756-711');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-982');
insert into can_conduct (lab_name, type_id) values ('Topco Associates llc', '36800-067');
insert into can_conduct (lab_name, type_id) values ('State of Florida DOH Central Pharmacy', '53808-0986');
insert into can_conduct (lab_name, type_id) values ('Unit Dose Services', '50436-6305');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-256');
insert into can_conduct (lab_name, type_id) values ('Aidarex Pharmaceuticals LLC', '33261-982');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-3058');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0088');
insert into can_conduct (lab_name, type_id) values ('Pfizer Consumer Healthcare', '0573-2880');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-5426');
insert into can_conduct (lab_name, type_id) values ('DSHealthcare', '0699-5720');
insert into can_conduct (lab_name, type_id) values ('ReadyMeds', '64205-222');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-5539');
insert into can_conduct (lab_name, type_id) values ('L''Oreal USA Products Inc', '49967-264');
insert into can_conduct (lab_name, type_id) values ('Indiana Botanic Gardens', '10578-053');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-3245');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1715');
insert into can_conduct (lab_name, type_id) values ('Mallinckrodt, Inc.', '0406-9025');
insert into can_conduct (lab_name, type_id) values ('Torrent Pharmaceuticals Limited', '13668-300');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-3123');
insert into can_conduct (lab_name, type_id) values ('Laser Pharmaceuticals LLC', '16477-136');
insert into can_conduct (lab_name, type_id) values ('HEALTHPOINT, LTD', '0064-5010');
insert into can_conduct (lab_name, type_id) values ('Matrixx Initiatives, Inc.', '62750-059');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-3129');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-0784');
insert into can_conduct (lab_name, type_id) values ('Reckitt Benckiser LLC', '63824-860');
insert into can_conduct (lab_name, type_id) values ('IVAX Pharmaceuticals, Inc.', '0172-7311');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-197');
insert into can_conduct (lab_name, type_id) values ('NCS HealthCare of KY, Inc dba Vangard Labs', '0615-7641');
insert into can_conduct (lab_name, type_id) values ('DIRECT RX', '61919-362');
insert into can_conduct (lab_name, type_id) values ('DIRECT RX', '61919-567');
insert into can_conduct (lab_name, type_id) values ('A-S Medication Solutions LLC', '54569-4586');
insert into can_conduct (lab_name, type_id) values ('Avon Products, Inc.', '10096-0154');
insert into can_conduct (lab_name, type_id) values ('Publix Super Markets Inc', '56062-050');
insert into can_conduct (lab_name, type_id) values ('STAT Rx USA LLC', '16590-002');
insert into can_conduct (lab_name, type_id) values ('KAISER FOUNDATION HOSPITALS', '0179-1118');
insert into can_conduct (lab_name, type_id) values ('Eight and Company', '61096-0032');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-1527');
insert into can_conduct (lab_name, type_id) values ('Hyland''s', '54973-9120');
insert into can_conduct (lab_name, type_id) values ('Wal-Mart Stores Inc', '49035-477');
insert into can_conduct (lab_name, type_id) values ('Sanofi Pasteur Inc.', '49281-800');
insert into can_conduct (lab_name, type_id) values ('Parfums Christian Dior', '61957-2105');
insert into can_conduct (lab_name, type_id) values ('Chain Drug Marketing Association', '63868-753');
insert into can_conduct (lab_name, type_id) values ('Major Pharmaceuticals', '0904-6408');
insert into can_conduct (lab_name, type_id) values ('Eisai Inc.', '62856-272');
insert into can_conduct (lab_name, type_id) values ('Eon Labs, Inc.', '0185-0117');
insert into can_conduct (lab_name, type_id) values ('H E B', '37808-288');
insert into can_conduct (lab_name, type_id) values ('PD-Rx Pharmaceuticals, Inc.', '55289-385');
insert into can_conduct (lab_name, type_id) values ('McKesson Packaging Services a business unit of McKesson Corporation', '63739-804');
insert into can_conduct (lab_name, type_id) values ('RXV', '14049-467');
insert into can_conduct (lab_name, type_id) values ('WALGREEN CO', '0363-1299');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2714');
insert into can_conduct (lab_name, type_id) values ('Baxter Healthcare Corporation', '0338-1109');
insert into can_conduct (lab_name, type_id) values ('Natural Creationa, Inc.', '43406-0075');
insert into can_conduct (lab_name, type_id) values ('Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.', '58232-0021');
insert into can_conduct (lab_name, type_id) values ('Procter & Gamble Manufacturing Company', '37000-355');
insert into can_conduct (lab_name, type_id) values ('The Dial Corporation', '54340-179');
insert into can_conduct (lab_name, type_id) values ('General Injectables & Vaccines, Inc.', '52584-910');
insert into can_conduct (lab_name, type_id) values ('PHI, Inc', '27789-911');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-1493');
insert into can_conduct (lab_name, type_id) values ('HEB', '37808-254');
insert into can_conduct (lab_name, type_id) values ('Valeant Pharmaceuticals North America LLC', '0187-5019');
insert into can_conduct (lab_name, type_id) values ('Dr. Donna Restivo DC', '62185-0005');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-5413');
insert into can_conduct (lab_name, type_id) values ('STAT Rx USA LLC', '42549-589');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-3119');
insert into can_conduct (lab_name, type_id) values ('Procter & Gamble Manufacturing Company', '37000-402');
insert into can_conduct (lab_name, type_id) values ('Ecomine Co Ltd', '51270-116');
insert into can_conduct (lab_name, type_id) values ('Dr. Reddy''s Laboratories Limited', '55111-545');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1134');
insert into can_conduct (lab_name, type_id) values ('Chattem, Inc.', '41167-3002');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-0083');
insert into can_conduct (lab_name, type_id) values ('Hawthorn Pharmaceuticals, Inc', '63717-333');
insert into can_conduct (lab_name, type_id) values ('Access Business Group LLC', '10056-710');
insert into can_conduct (lab_name, type_id) values ('Silarx Pharmaceuticals,Inc', '54838-107');
insert into can_conduct (lab_name, type_id) values ('Bryant Ranch Prepack', '63629-2614');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1944');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-3513');
insert into can_conduct (lab_name, type_id) values ('Paramesh Banerji Life Sciences LLC', '69152-0110');
insert into can_conduct (lab_name, type_id) values ('BJWC', '68391-344');
insert into can_conduct (lab_name, type_id) values ('New World Imports, Inc', '51824-035');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-7186');
insert into can_conduct (lab_name, type_id) values ('Ventura Corporation LTD', '13537-280');
insert into can_conduct (lab_name, type_id) values ('TRP Company', '17312-018');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0190');
insert into can_conduct (lab_name, type_id) values ('Heritage Pharmaceuticals Inc.', '23155-066');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2586');
insert into can_conduct (lab_name, type_id) values ('American Health Packaging', '68084-740');
insert into can_conduct (lab_name, type_id) values ('Home Sweet Homeopathics', '59667-0046');
insert into can_conduct (lab_name, type_id) values ('St. Marys Medical Park Pharmacy', '60760-121');
insert into can_conduct (lab_name, type_id) values ('Paddock Laboratories, Inc.', '0574-0069');
insert into can_conduct (lab_name, type_id) values ('Allure Labs, Inc.', '62742-4050');
insert into can_conduct (lab_name, type_id) values ('Physician Therapeutics LLC', '68405-118');
insert into can_conduct (lab_name, type_id) values ('Universal holdings I LLC dba Smith Brothers Company', '76461-021');
insert into can_conduct (lab_name, type_id) values ('Parfums Christian Dior', '61957-1510');
insert into can_conduct (lab_name, type_id) values ('Contract Pharmacy Services-PA', '67046-428');
insert into can_conduct (lab_name, type_id) values ('Autumn Harp, Inc.', '51514-0315');
insert into can_conduct (lab_name, type_id) values ('McKesson', '49348-960');
insert into can_conduct (lab_name, type_id) values ('Procter & Gamble Manufacturing Company', '37000-178');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2909');
insert into can_conduct (lab_name, type_id) values ('Otsuka America Pharmaceutical, Inc.', '59148-013');
insert into can_conduct (lab_name, type_id) values ('Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.', '58232-1403');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-6751');
insert into can_conduct (lab_name, type_id) values ('Procter & Gamble Manufacturing Company', '37000-713');
insert into can_conduct (lab_name, type_id) values ('Ranbaxy Laboratories Ltd.', '63304-652');
insert into can_conduct (lab_name, type_id) values ('Molton Brown LTD (UK)', '68814-145');
insert into can_conduct (lab_name, type_id) values ('Deb USA, Inc.', '11084-111');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0913');
insert into can_conduct (lab_name, type_id) values ('Supervalu Inc', '41163-368');
insert into can_conduct (lab_name, type_id) values ('SHISEIDO AMERICAS CORPORATION', '58411-103');
insert into can_conduct (lab_name, type_id) values ('West-ward Pharmaceutical Corp', '0143-9750');
insert into can_conduct (lab_name, type_id) values ('Sun Pharmaceutical Industries Limited', '62756-461');
insert into can_conduct (lab_name, type_id) values ('Energique, Inc.', '44911-0059');
insert into can_conduct (lab_name, type_id) values ('Actavis Pharma, Inc.', '52544-154');
insert into can_conduct (lab_name, type_id) values ('Meijer Distribution Inc', '41250-394');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-376');
insert into can_conduct (lab_name, type_id) values ('Inel Cosmetics Co., Ltd.', '43526-101');
insert into can_conduct (lab_name, type_id) values ('Golden State Medical Supply, Inc.', '60429-023');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-490');
insert into can_conduct (lab_name, type_id) values ('Walgreen Company', '0363-0578');
insert into can_conduct (lab_name, type_id) values ('WG Critical Care, LLC', '44567-804');
insert into can_conduct (lab_name, type_id) values ('Denison Pharmaceuticals, Inc.', '0295-1223');
insert into can_conduct (lab_name, type_id) values ('Reckitt Benckiser LLC', '63824-041');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-6400');
insert into can_conduct (lab_name, type_id) values ('VistaPharm Inc.', '66689-036');
insert into can_conduct (lab_name, type_id) values ('Mikart, Inc.', '46672-844');
insert into can_conduct (lab_name, type_id) values ('Medline Industries, Inc.', '53329-082');
insert into can_conduct (lab_name, type_id) values ('Valeant Pharmaceuticals North America LLC', '0187-0731');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-536');
insert into can_conduct (lab_name, type_id) values ('Meijer Distribution Inc', '41250-021');
insert into can_conduct (lab_name, type_id) values ('Golden State Medical Supply, Inc.', '60429-272');
insert into can_conduct (lab_name, type_id) values ('SJ Creations, Inc.', '43269-827');
insert into can_conduct (lab_name, type_id) values ('Hospira, Inc.', '0409-4777');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-1138');
insert into can_conduct (lab_name, type_id) values ('CRC (Cosmoceutical Research Center)', '66538-501');
insert into can_conduct (lab_name, type_id) values ('Preferred Pharmaceuticals, Inc.', '68788-9949');
insert into can_conduct (lab_name, type_id) values ('L. Perrigo Company', '0113-0567');
insert into can_conduct (lab_name, type_id) values ('Aphena Pharma Solutions - Tennessee, LLC', '67544-697');
insert into can_conduct (lab_name, type_id) values ('Supervalu, Inc', '41163-871');
insert into can_conduct (lab_name, type_id) values ('Perrigo New York Inc', '45802-216');
insert into can_conduct (lab_name, type_id) values ('SWEDISH ORPHAN BIOVITRUM AB (PUBL)', '66658-102');
insert into can_conduct (lab_name, type_id) values ('Ventura Corporation (San Juan, P.R)', '13537-359');
insert into can_conduct (lab_name, type_id) values ('Rebel Distirbutors Corp', '21695-491');
insert into can_conduct (lab_name, type_id) values ('Laboratoires Anios', '62169-203');
insert into can_conduct (lab_name, type_id) values ('Global Pharmaceuticals, Division of Impax Laboratories, Inc.', '0115-1315');
insert into can_conduct (lab_name, type_id) values ('Becton Dickinson and Company', '17271-245');
insert into can_conduct (lab_name, type_id) values ('CRH Medical Corporation', '69041-002');
insert into can_conduct (lab_name, type_id) values ('Washington Homeopathic Products', '68428-085');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-5367');
insert into can_conduct (lab_name, type_id) values ('RedPharm Drug Inc.', '67296-0538');
insert into can_conduct (lab_name, type_id) values ('TIME CAP LABORATORIES, INC', '49483-222');
insert into can_conduct (lab_name, type_id) values ('Upstate Pharma, LLC', '65580-304');
insert into can_conduct (lab_name, type_id) values ('Haemonetics Corporation', '57826-420');
insert into can_conduct (lab_name, type_id) values ('MAKEUP ART COSMETICS', '40046-0042');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0184');
insert into can_conduct (lab_name, type_id) values ('Merck Sharp & Dohme Corp.', '0085-4347');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1968');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health (Leader) 49781', '49781-046');
insert into can_conduct (lab_name, type_id) values ('Warner Chilcott (US), LLC', '0430-0010');
insert into can_conduct (lab_name, type_id) values ('Lumene Oy', '67692-000');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-2023');
insert into can_conduct (lab_name, type_id) values ('Preferred Pharmaceuticals, Inc', '68788-9086');
insert into can_conduct (lab_name, type_id) values ('Arbonne International, LLC', '42508-265');
insert into can_conduct (lab_name, type_id) values ('Allergy Laboratories, Inc.', '54575-914');
insert into can_conduct (lab_name, type_id) values ('Qualitest Pharmaceuticals', '0603-5168');
insert into can_conduct (lab_name, type_id) values ('Breckenridge Pharmaceutical, Inc.', '51991-817');
insert into can_conduct (lab_name, type_id) values ('Blaine Labs Inc.', '65373-401');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1902');
insert into can_conduct (lab_name, type_id) values ('Neutrogena Corporation', '10812-348');
insert into can_conduct (lab_name, type_id) values ('Pliva Inc.', '50111-901');
insert into can_conduct (lab_name, type_id) values ('NATURE REPUBLIC CO., LTD.', '51346-087');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2958');
insert into can_conduct (lab_name, type_id) values ('Walgreen Company', '0363-8127');
insert into can_conduct (lab_name, type_id) values ('Shopko Stores Operating Co., LLC', '37012-335');
insert into can_conduct (lab_name, type_id) values ('Ventura Corporation (San Juan, P.R)', '13537-322');
insert into can_conduct (lab_name, type_id) values ('General Injectables & Vaccines, Inc', '52584-476');
insert into can_conduct (lab_name, type_id) values ('NDC National Distribution & Contracting, Inc.', '43128-118');
insert into can_conduct (lab_name, type_id) values ('Energetix Corp', '64578-0080');
insert into can_conduct (lab_name, type_id) values ('RUGBY LABORATORIES, INC.', '0536-3218');
insert into can_conduct (lab_name, type_id) values ('Geiss, Destin & Dunn, Inc', '50804-831');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-780');
insert into can_conduct (lab_name, type_id) values ('Wakefern Food Corporation', '41190-544');
insert into can_conduct (lab_name, type_id) values ('Watson Laboratories, Inc.', '0591-0800');
insert into can_conduct (lab_name, type_id) values ('June Jacobs Laboratories LLC', '65278-007');
insert into can_conduct (lab_name, type_id) values ('Preferred Pharmaceuticals, Inc.', '68788-9515');
insert into can_conduct (lab_name, type_id) values ('Jubilant Cadista Pharmaceuticals Inc.', '59746-333');
insert into can_conduct (lab_name, type_id) values ('Beiersdorf Inc', '10356-822');
insert into can_conduct (lab_name, type_id) values ('Mylan Institutional Inc.', '51079-563');
insert into can_conduct (lab_name, type_id) values ('Rimmel Inc.', '76485-1011');
insert into can_conduct (lab_name, type_id) values ('Robinson Pharma, Inc.', '59995-001');
insert into can_conduct (lab_name, type_id) values ('FREDS, INC', '55315-100');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-310');
insert into can_conduct (lab_name, type_id) values ('Wal-Mart Stores Inc', '49035-999');
insert into can_conduct (lab_name, type_id) values ('Perrigo New York Inc', '45802-338');
insert into can_conduct (lab_name, type_id) values ('Wal-Mart Stores Inc', '49035-637');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-1516');
insert into can_conduct (lab_name, type_id) values ('Baxter Healthcare Corporation', '0338-0004');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-382');
insert into can_conduct (lab_name, type_id) values ('Amphastar Pharmaceuticals, Inc.', '0548-9061');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-5436');
insert into can_conduct (lab_name, type_id) values ('Medi-Physics Inc.', '17156-618');
insert into can_conduct (lab_name, type_id) values ('CHANEL PARFUMS BEAUTE', '68745-1050');
insert into can_conduct (lab_name, type_id) values ('McKesson', '49348-982');
insert into can_conduct (lab_name, type_id) values ('Virtus Pharmaceuticals', '76439-302');
insert into can_conduct (lab_name, type_id) values ('Novartis Pharmaceuticals Corporation', '0078-0357');
insert into can_conduct (lab_name, type_id) values ('Dr.Reddy''s Laboratories Limited', '55111-340');
insert into can_conduct (lab_name, type_id) values ('Putney Inc', '26637-322');
insert into can_conduct (lab_name, type_id) values ('Cephalon, Inc.', '63459-508');
insert into can_conduct (lab_name, type_id) values ('Breckenridge Pharmaceutical, Inc.', '51991-294');
insert into can_conduct (lab_name, type_id) values ('Amercare Products, Inc', '51460-4943');
insert into can_conduct (lab_name, type_id) values ('State of Florida DOH Central Pharmacy', '53808-1045');
insert into can_conduct (lab_name, type_id) values ('Wakefern Food Corporation', '41190-852');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0249');
insert into can_conduct (lab_name, type_id) values ('McKesson Packaging Services Business Unit of McKesson Corporation', '63739-251');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-2073');
insert into can_conduct (lab_name, type_id) values ('Galderma Laboratories, L.P.', '0299-3820');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '37205-940');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0054');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical DBA Quality Care Products LLC', '55700-025');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0060');
insert into can_conduct (lab_name, type_id) values ('Aurobindo Pharma Limited', '65862-038');
insert into can_conduct (lab_name, type_id) values ('Kroger Company', '30142-054');
insert into can_conduct (lab_name, type_id) values ('Cargo Cosmetics Corp.', '76053-004');
insert into can_conduct (lab_name, type_id) values ('Bryant Ranch Prepack', '63629-4606');
insert into can_conduct (lab_name, type_id) values ('Larasan Pharmaceutical Corporation', '54641-005');
insert into can_conduct (lab_name, type_id) values ('Rebel Distributors Corp', '42254-066');
insert into can_conduct (lab_name, type_id) values ('Avon Products, Inc', '10096-9488');
insert into can_conduct (lab_name, type_id) values ('Bryant Ranch Prepack', '63629-1809');
insert into can_conduct (lab_name, type_id) values ('Dr Elena M Morreale', '50813-0009');
insert into can_conduct (lab_name, type_id) values ('ILEX Consumer Products Group, LLC (ST. JOSEPH)', '76000-370');
insert into can_conduct (lab_name, type_id) values ('Bolero Home Decor, Inc.', '57469-011');
insert into can_conduct (lab_name, type_id) values ('American Health Packaging', '68084-799');
insert into can_conduct (lab_name, type_id) values ('NCS HealthCare of KY, Inc dba Vangard Labs', '0615-1501');
insert into can_conduct (lab_name, type_id) values ('Sun Pharma Global FZE', '47335-678');
insert into can_conduct (lab_name, type_id) values ('STAT RX USA LLC', '16590-282');
insert into can_conduct (lab_name, type_id) values ('Qualitest Pharmaceuticals', '0603-1147');
insert into can_conduct (lab_name, type_id) values ('Uriel Pharmacy Inc.', '48951-8226');
insert into can_conduct (lab_name, type_id) values ('A-S Medication Solutions LLC', '54569-6497');
insert into can_conduct (lab_name, type_id) values ('Autumn Harp, Inc', '51514-0217');
insert into can_conduct (lab_name, type_id) values ('Aaron Industries, Inc.', '49580-0106');
insert into can_conduct (lab_name, type_id) values ('J. A. Cosmetics U.S. INC', '76354-012');
insert into can_conduct (lab_name, type_id) values ('Par Pharmaceutical, Inc.', '49884-034');
insert into can_conduct (lab_name, type_id) values ('Fitness Systems Mfg Corp', '51609-0001');
insert into can_conduct (lab_name, type_id) values ('McKesson', '49348-890');
insert into can_conduct (lab_name, type_id) values ('Blenheim Pharmacal, Inc.', '10544-541');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-3323');
insert into can_conduct (lab_name, type_id) values ('Qualitest Pharmaceuticals', '0603-1481');
insert into can_conduct (lab_name, type_id) values ('Rimmel Inc.', '76485-1037');
insert into can_conduct (lab_name, type_id) values ('AFFLABS, Affiliated Laboratories, A Division of AFFLINK', '54057-682');
insert into can_conduct (lab_name, type_id) values ('Ther-Rx Corporation', '64011-246');
insert into can_conduct (lab_name, type_id) values ('The Torrance Company', '0389-0486');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-4155');
insert into can_conduct (lab_name, type_id) values ('BioActive Nutritional, Inc', '43857-0280');
insert into can_conduct (lab_name, type_id) values ('Wockhardt USA LLC.', '64679-954');
insert into can_conduct (lab_name, type_id) values ('Bryant Ranch Prepack', '63629-4855');
insert into can_conduct (lab_name, type_id) values ('AvKARE, Inc.', '42291-253');
insert into can_conduct (lab_name, type_id) values ('Target Corporation', '11673-690');
insert into can_conduct (lab_name, type_id) values ('Meda Pharmaceuticals Inc.', '0037-0521');
insert into can_conduct (lab_name, type_id) values ('HOE HIN PAK FAH YEOW MANUFACTORY LTD', '48256-0041');
insert into can_conduct (lab_name, type_id) values ('AMERICAN SALES COMPANY', '41520-281');
insert into can_conduct (lab_name, type_id) values ('Amneal Pharmaceuticals, LLC', '65162-809');
insert into can_conduct (lab_name, type_id) values ('PEN Prep LLC', '76334-001');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-508');
insert into can_conduct (lab_name, type_id) values ('Allergy Laboratories, Inc.', '54575-959');
insert into can_conduct (lab_name, type_id) values ('Apple Products, Inc.', '67147-544');
insert into can_conduct (lab_name, type_id) values ('Major Pharmaceuticals', '0904-7927');
insert into can_conduct (lab_name, type_id) values ('Dispensing Solutions, Inc.', '66336-673');
insert into can_conduct (lab_name, type_id) values ('Lannett Company, Inc.', '0527-1349');
insert into can_conduct (lab_name, type_id) values ('STAT Rx USA LLC', '42549-640');
insert into can_conduct (lab_name, type_id) values ('Butler Gas Products Company', '10189-001');
insert into can_conduct (lab_name, type_id) values ('Bare Escentuals Beauty Inc.', '98132-889');
insert into can_conduct (lab_name, type_id) values ('DZA Brands LLC', '55316-595');
insert into can_conduct (lab_name, type_id) values ('Sun Pharma Global FZE', '47335-678');
insert into can_conduct (lab_name, type_id) values ('ABBP (ARRINGTON, BATTLE, BELL & PERRY), LLC', '50462-110');
insert into can_conduct (lab_name, type_id) values ('Roxane Laboratories, Inc', '0054-0002');
insert into can_conduct (lab_name, type_id) values ('H and P Industries, Inc. dba Triad Group', '50730-8717');
insert into can_conduct (lab_name, type_id) values ('Medical Chemical Corporation', '12745-177');
insert into can_conduct (lab_name, type_id) values ('Sunmark', '49348-923');
insert into can_conduct (lab_name, type_id) values ('Eli Lilly and Company', '0002-7510');
insert into can_conduct (lab_name, type_id) values ('Browne Hansen LLC', '56149-002');
insert into can_conduct (lab_name, type_id) values ('American Health Packaging', '68084-565');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-2060');
insert into can_conduct (lab_name, type_id) values ('BioComp Pharma, Inc.', '44523-607');
insert into can_conduct (lab_name, type_id) values ('Baxter Healthcare Corporation', '0941-0415');
insert into can_conduct (lab_name, type_id) values ('Preferred Pharmaceuticals, Inc', '68788-9820');
insert into can_conduct (lab_name, type_id) values ('SUPERVALU INC.', '41163-531');
insert into can_conduct (lab_name, type_id) values ('Waxie Sanitary Supply', '61666-001');
insert into can_conduct (lab_name, type_id) values ('West-Ward Pharmaceutical Corp', '0143-1455');
insert into can_conduct (lab_name, type_id) values ('Teva Parenteral Medicines, Inc.', '0703-0051');
insert into can_conduct (lab_name, type_id) values ('Procter & Gamble Manufacturing Company', '37000-278');
insert into can_conduct (lab_name, type_id) values ('Teva Parenteral Medicines, Inc.', '0703-5233');
insert into can_conduct (lab_name, type_id) values ('Major Pharmaceuticals', '0904-6288');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-2380');
insert into can_conduct (lab_name, type_id) values ('VALUE MERCHANDISERS COMPANY, INC.', '63941-249');
insert into can_conduct (lab_name, type_id) values ('MOBERG PHARMA NORTH AMERICA LLC', '16864-011');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-048');
insert into can_conduct (lab_name, type_id) values ('St Marys Medical Park Pharmacy', '60760-429');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0422');
insert into can_conduct (lab_name, type_id) values ('Wyeth Consumer Healthcare', '0573-2400');
insert into can_conduct (lab_name, type_id) values ('Select Brand', '15127-943');
insert into can_conduct (lab_name, type_id) values ('Rebel Distributors Corp', '21695-996');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-1089');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0735');
insert into can_conduct (lab_name, type_id) values ('Contract Pharmacy Services-PA', '67046-281');
insert into can_conduct (lab_name, type_id) values ('Cadila Healthcare Limited', '65841-027');
insert into can_conduct (lab_name, type_id) values ('Liddell Laboratories, Inc.', '50845-0138');
insert into can_conduct (lab_name, type_id) values ('Moore Medical LLC', '55670-150');
insert into can_conduct (lab_name, type_id) values ('G&W Laboratories, Inc.', '0713-0252');
insert into can_conduct (lab_name, type_id) values ('Laboratoires Clarins S.A.', '58668-1031');
insert into can_conduct (lab_name, type_id) values ('A-S Medication Solutions LLC', '54569-2590');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-0075');
insert into can_conduct (lab_name, type_id) values ('KRAMER NOVIS', '52083-620');
insert into can_conduct (lab_name, type_id) values ('Owen Biosciences, Inc.', '59958-200');
insert into can_conduct (lab_name, type_id) values ('Topco Associates LLC', '36800-096');
insert into can_conduct (lab_name, type_id) values ('Sagent Pharmaceuticals', '25021-135');
insert into can_conduct (lab_name, type_id) values ('Aplicare, Inc.', '52380-2802');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0653');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0764');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-4836');
insert into can_conduct (lab_name, type_id) values ('Procter & Gamble Manufacturing Company', '37000-470');
insert into can_conduct (lab_name, type_id) values ('Avon Products, Inc.', '10096-0264');
insert into can_conduct (lab_name, type_id) values ('ReadyMeds', '64205-739');
insert into can_conduct (lab_name, type_id) values ('Nesher Pharmaceuticals (USA) LLC', '51477-001');
insert into can_conduct (lab_name, type_id) values ('Golden State Medical Supply, Inc.', '60429-279');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2845');
insert into can_conduct (lab_name, type_id) values ('WOONSOCKET PRESCRIPTION CENTER,INCORPORATED', '59779-404');
insert into can_conduct (lab_name, type_id) values ('Clinical Solutions Wholesale', '58118-8343');
insert into can_conduct (lab_name, type_id) values ('Tween Brands Inc', '60637-003');
insert into can_conduct (lab_name, type_id) values ('Wal-Mart Stores Inc', '49035-098');
insert into can_conduct (lab_name, type_id) values ('OMP, INC.', '62032-513');
insert into can_conduct (lab_name, type_id) values ('Unit Dose Services', '50436-0873');
insert into can_conduct (lab_name, type_id) values ('Greenstone LLC', '59762-0935');
insert into can_conduct (lab_name, type_id) values ('Central Oxygen Inc', '54829-001');
insert into can_conduct (lab_name, type_id) values ('Qualitest Pharmaceuticals', '0603-5439');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-822');
insert into can_conduct (lab_name, type_id) values ('SJ Creations, Inc.', '43269-808');
insert into can_conduct (lab_name, type_id) values ('Tri-Coastal Design Company Inc.', '49852-202');
insert into can_conduct (lab_name, type_id) values ('Chain Drug Marketing Association', '63868-165');
insert into can_conduct (lab_name, type_id) values ('Newton Laboratories, Inc.', '55714-2320');
insert into can_conduct (lab_name, type_id) values ('Amneal Pharmaceuticals', '65162-513');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-1800');
insert into can_conduct (lab_name, type_id) values ('Clinical Solutions Wholesale', '58118-0260');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-812');
insert into can_conduct (lab_name, type_id) values ('Hospira, Inc.', '0409-6141');
insert into can_conduct (lab_name, type_id) values ('United Exchange Corp.', '65923-565');
insert into can_conduct (lab_name, type_id) values ('Humco Holding Group, Inc.', '0395-0243');
insert into can_conduct (lab_name, type_id) values ('DHC USA Incorporated', '63433-122');
insert into can_conduct (lab_name, type_id) values ('Atlantic Biologicals Corps', '17856-0788');
insert into can_conduct (lab_name, type_id) values ('Mckesson', '62011-0223');
insert into can_conduct (lab_name, type_id) values ('AvPAK', '50268-730');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0050');
insert into can_conduct (lab_name, type_id) values ('Amerisource Bergen', '46122-144');
insert into can_conduct (lab_name, type_id) values ('Wockhardt USA LLC.', '64679-983');
insert into can_conduct (lab_name, type_id) values ('Star Pharmaceuticals LLC', '0076-0903');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-546');
insert into can_conduct (lab_name, type_id) values ('ART COSMETICS SRL', '42221-0006');
insert into can_conduct (lab_name, type_id) values ('H E B', '37808-485');
insert into can_conduct (lab_name, type_id) values ('DSHealthcare', '0699-5750');
insert into can_conduct (lab_name, type_id) values ('Jafra Cosmetics International Inc', '68828-085');
insert into can_conduct (lab_name, type_id) values ('FAMILY DOLLAR', '55319-323');
insert into can_conduct (lab_name, type_id) values ('Pernix Therapeutics, LLC', '65224-700');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0431');
insert into can_conduct (lab_name, type_id) values ('Shasun Pharmaceuticals Limited', '57910-403');
insert into can_conduct (lab_name, type_id) values ('EBAIN Corporation Co., Ltd.', '62242-030');
insert into can_conduct (lab_name, type_id) values ('Mutual Pharmaceutical Company, Inc.', '53489-478');
insert into can_conduct (lab_name, type_id) values ('Boehringer Ingelheim Pharmaceuticals, Inc.', '0597-0125');
insert into can_conduct (lab_name, type_id) values ('PD-Rx Pharmaceuticals, Inc.', '55289-217');
insert into can_conduct (lab_name, type_id) values ('Exact-Rx, Inc.', '42808-405');
insert into can_conduct (lab_name, type_id) values ('E-Z-EM Canada Inc', '32909-804');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-5688');
insert into can_conduct (lab_name, type_id) values ('Rugby Laboratories, Inc.', '0536-1002');
insert into can_conduct (lab_name, type_id) values ('International Beauty Exchange', '66129-140');
insert into can_conduct (lab_name, type_id) values ('Sandoz Inc', '0781-5017');
insert into can_conduct (lab_name, type_id) values ('Zydus Pharmaceuticals USA Inc', '68382-202');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical DBA Quality Care Products LLC', '49999-957');
insert into can_conduct (lab_name, type_id) values ('Neutrogena Corporation', '10812-433');
insert into can_conduct (lab_name, type_id) values ('Erno Laszlo, Inc.', '57913-2834');
insert into can_conduct (lab_name, type_id) values ('Natural Creations, Inc.', '43406-0047');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-3276');
insert into can_conduct (lab_name, type_id) values ('H.J. Harkins Company, Inc.', '52959-413');
insert into can_conduct (lab_name, type_id) values ('American Health Packaging', '68084-823');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0136');
insert into can_conduct (lab_name, type_id) values ('Sierra Mountain Minerals Inc. d/b/a Sierra Sil Health Inc.', '50802-001');
insert into can_conduct (lab_name, type_id) values ('Meijer Distribution Inc', '41250-548');
insert into can_conduct (lab_name, type_id) values ('Jiangsu Province JianErKang Medical Dressing Co. ,Ltd.', '34645-5028');
insert into can_conduct (lab_name, type_id) values ('Certus Medical, Inc.', '75990-576');
insert into can_conduct (lab_name, type_id) values ('Hyland''s', '54973-2921');
insert into can_conduct (lab_name, type_id) values ('APP Pharmaceuticals, LLC', '63323-485');
insert into can_conduct (lab_name, type_id) values ('Navajo Manuracturing Company', '67751-140');
insert into can_conduct (lab_name, type_id) values ('Elizabeth Arden, Inc', '67938-1024');
insert into can_conduct (lab_name, type_id) values ('North Safety Products', '0498-0303');
insert into can_conduct (lab_name, type_id) values ('Heritage Pharmaceuticals Inc.', '23155-168');
insert into can_conduct (lab_name, type_id) values ('Reckitt Benckiser LLC', '63824-354');
insert into can_conduct (lab_name, type_id) values ('Bryant Ranch Prepack', '63629-4995');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0003');
insert into can_conduct (lab_name, type_id) values ('H E B', '37808-190');
insert into can_conduct (lab_name, type_id) values ('West-ward Pharmaceutical Corp.', '0641-6039');
insert into can_conduct (lab_name, type_id) values ('SOMA Biotechnology Co., Ltd', '58370-9001');
insert into can_conduct (lab_name, type_id) values ('Contract Pharmacal Corp', '10267-1006');
insert into can_conduct (lab_name, type_id) values ('Humphries, Inc.', '52695-001');
insert into can_conduct (lab_name, type_id) values ('Sandoz Inc', '0781-1078');
insert into can_conduct (lab_name, type_id) values ('Western Family Foods, Inc.', '55312-233');
insert into can_conduct (lab_name, type_id) values ('Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.', '58232-0032');
insert into can_conduct (lab_name, type_id) values ('Apotex Corp', '60505-3573');
insert into can_conduct (lab_name, type_id) values ('Allure Labs Inc.', '62742-4064');
insert into can_conduct (lab_name, type_id) values ('West-Ward Pharmaceutical Corp', '0143-0170');
insert into can_conduct (lab_name, type_id) values ('Greenbrier International, Inc.', '33992-1068');
insert into can_conduct (lab_name, type_id) values ('Prasco Laboratories', '66993-053');
insert into can_conduct (lab_name, type_id) values ('Major Pharmaceuticals', '00904-5899');
insert into can_conduct (lab_name, type_id) values ('Rite Aid Corporation', '11822-0616');
insert into can_conduct (lab_name, type_id) values ('Allergy Laboratories, Inc.', '54575-353');
insert into can_conduct (lab_name, type_id) values ('Forces of Nature', '51393-7599');
insert into can_conduct (lab_name, type_id) values ('KAISER FOUNDATION HOSPITALS', '0179-0087');
insert into can_conduct (lab_name, type_id) values ('WAL-MART STORES INC', '49035-723');
insert into can_conduct (lab_name, type_id) values ('Alternate Pharmacy', '49304-0013');
insert into can_conduct (lab_name, type_id) values ('MineralBio', '50499-100');
insert into can_conduct (lab_name, type_id) values ('H E B', '37808-180');
insert into can_conduct (lab_name, type_id) values ('Native Remedies, LLC', '68703-082');
insert into can_conduct (lab_name, type_id) values ('Universal Holdings I LLC', '76461-005');
insert into can_conduct (lab_name, type_id) values ('Rugby Laboratories', '0536-1875');
insert into can_conduct (lab_name, type_id) values ('NATURE REPUBLIC CO., LTD.', '51346-074');
insert into can_conduct (lab_name, type_id) values ('CCA Industries, Inc.', '61543-7755');
insert into can_conduct (lab_name, type_id) values ('Cadila Pharmaceuticals Limited', '65691-0106');
insert into can_conduct (lab_name, type_id) values ('Hospira, Inc.', '0409-4057');
insert into can_conduct (lab_name, type_id) values ('Cleanphirst, LLC', '52138-100');
insert into can_conduct (lab_name, type_id) values ('Gano Welding Supplies, Inc', '49363-9901');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-688');
insert into can_conduct (lab_name, type_id) values ('Xspire Pharma', '42195-600');
insert into can_conduct (lab_name, type_id) values ('Hospira, Inc.', '0409-7248');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0532');
insert into can_conduct (lab_name, type_id) values ('L Perrigo Company', '0113-0081');
insert into can_conduct (lab_name, type_id) values ('HOMEOLAB USA INC.', '60512-6152');
insert into can_conduct (lab_name, type_id) values ('Unifirst First Aid Corporation', '47682-200');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-3230');
insert into can_conduct (lab_name, type_id) values ('Teva Parenteral Medicines, Inc', '0703-4686');
insert into can_conduct (lab_name, type_id) values ('Sandoz Inc', '0781-5720');
insert into can_conduct (lab_name, type_id) values ('OMP, INC.', '62032-117');
insert into can_conduct (lab_name, type_id) values ('Aidarex Pharmaceuticals LLC', '33261-600');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1301');
insert into can_conduct (lab_name, type_id) values ('L''Oreal USA Products Inc', '49967-882');
insert into can_conduct (lab_name, type_id) values ('Mylan Institutional LLC', '67457-431');
insert into can_conduct (lab_name, type_id) values ('Ventura Corporation (San Juan, P.R)', '13537-341');
insert into can_conduct (lab_name, type_id) values ('BioActive Nutritional, Inc.', '43857-0171');
insert into can_conduct (lab_name, type_id) values ('Gen-Source Rx', '52343-026');
insert into can_conduct (lab_name, type_id) values ('Oceanside Pharmaceuticals', '68682-302');
insert into can_conduct (lab_name, type_id) values ('Apotheca, Inc.', '12634-908');
insert into can_conduct (lab_name, type_id) values ('Baxter Healthcare Corporation', '0944-4303');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0502');
insert into can_conduct (lab_name, type_id) values ('SHISEIDO AMERICAS CORPORATION', '58411-153');
insert into can_conduct (lab_name, type_id) values ('Ultra Seal Corporation', '42213-162');
insert into can_conduct (lab_name, type_id) values ('Dr Reddys Laboratories Inc', '43598-210');
insert into can_conduct (lab_name, type_id) values ('Carlsbad Technology, Inc.', '61442-202');
insert into can_conduct (lab_name, type_id) values ('Amneal-Agila, LLC', '53150-247');
insert into can_conduct (lab_name, type_id) values ('CHANEL PARFUMS BEAUTE', '68745-1026');
insert into can_conduct (lab_name, type_id) values ('Rij Pharmaceutical Corporation', '53807-220');
insert into can_conduct (lab_name, type_id) values ('Certus Medical, Inc.', '75990-783');
insert into can_conduct (lab_name, type_id) values ('General Injectables & Vaccines, Inc', '52584-262');
insert into can_conduct (lab_name, type_id) values ('NCS HealthCare of KY, Inc dba Vangard Labs', '0615-7554');
insert into can_conduct (lab_name, type_id) values ('WG Critical Care, LLC', '44567-504');
insert into can_conduct (lab_name, type_id) values ('Harris Teeter', '72036-311');
insert into can_conduct (lab_name, type_id) values ('Energizer Personal Care LLC', '63354-730');
insert into can_conduct (lab_name, type_id) values ('American Health Packaging', '68084-399');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-7850');
insert into can_conduct (lab_name, type_id) values ('Walgreen Company', '0363-0957');
insert into can_conduct (lab_name, type_id) values ('F&CO Co., Ltd.', '69106-080');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1915');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-4658');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-2887');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-4336');
insert into can_conduct (lab_name, type_id) values ('Conopco Inc. d/b/a Unilever', '64942-1320');
insert into can_conduct (lab_name, type_id) values ('Philosophy', '50184-1032');
insert into can_conduct (lab_name, type_id) values ('STAT Rx USA LLC', '16590-423');
insert into can_conduct (lab_name, type_id) values ('Family Dollar Services Inc', '55319-173');
insert into can_conduct (lab_name, type_id) values ('Amneal Pharmaceuticals of New York, LLC', '53746-103');
insert into can_conduct (lab_name, type_id) values ('Uriel Pharmacy Inc.', '48951-4099');
insert into can_conduct (lab_name, type_id) values ('Conney Safety Products, LLC', '61245-116');
insert into can_conduct (lab_name, type_id) values ('Clinical Therapeutic Solutions', '44577-704');
insert into can_conduct (lab_name, type_id) values ('Watson Laboratories, Inc.', '0591-3630');
insert into can_conduct (lab_name, type_id) values ('Major Pharmaceuticals', '0904-6266');
insert into can_conduct (lab_name, type_id) values ('H E B', '37808-188');
insert into can_conduct (lab_name, type_id) values ('Premier Value', '68016-281');
insert into can_conduct (lab_name, type_id) values ('Walgreen Company', '0363-1003');
insert into can_conduct (lab_name, type_id) values ('Nartex Laboratorios Homeopaticos, S.A. De C.V.', '34666-003');
insert into can_conduct (lab_name, type_id) values ('Shanghai Weierya Daily Chemicals Factory', '58194-012');
insert into can_conduct (lab_name, type_id) values ('Lehigh Valley Technologies, Inc.', '64950-353');
insert into can_conduct (lab_name, type_id) values ('Natural Health Supply', '64117-123');
insert into can_conduct (lab_name, type_id) values ('Rij Pharmaceutical Corporation', '53807-408');
insert into can_conduct (lab_name, type_id) values ('Walgreen Company', '0363-1005');
insert into can_conduct (lab_name, type_id) values ('Advance Pharmaceutical Inc.', '17714-019');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-5827');
insert into can_conduct (lab_name, type_id) values ('Space Brands Limited', '61601-0082');
insert into can_conduct (lab_name, type_id) values ('NCS HealthCare of KY, Inc dba Vangard Labs', '0615-4529');
insert into can_conduct (lab_name, type_id) values ('NATURE REPUBLIC CO., LTD.', '51346-248');
insert into can_conduct (lab_name, type_id) values ('Rebel Distributors Corp.', '21695-513');
insert into can_conduct (lab_name, type_id) values ('Guerlain S.A', '49817-0055');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-4236');
insert into can_conduct (lab_name, type_id) values ('Pliva Inc.', '50111-648');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-5249');
insert into can_conduct (lab_name, type_id) values ('STAT Rx USA LLC', '16590-163');
insert into can_conduct (lab_name, type_id) values ('WOMENS CHOICE PHARMACEUTICALS LLC', '50967-219');
insert into can_conduct (lab_name, type_id) values ('McKesson Contract Packaging', '76237-173');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-025');
insert into can_conduct (lab_name, type_id) values ('Sanofi Pasteur, Inc', '49281-183');
insert into can_conduct (lab_name, type_id) values ('Physicians Total Care, Inc.', '54868-5787');
insert into can_conduct (lab_name, type_id) values ('Airgas National Welders', '11896-0019');
insert into can_conduct (lab_name, type_id) values ('Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', '0206-2413');
insert into can_conduct (lab_name, type_id) values ('State of Florida DOH Central Pharmacy', '53808-0730');
insert into can_conduct (lab_name, type_id) values ('Wockhardt USA LLC.', '64679-728');
insert into can_conduct (lab_name, type_id) values ('McKesson (Sunmark)', '49348-062');
insert into can_conduct (lab_name, type_id) values ('Lancaster S.A.M.', '59351-0322');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '52125-851');
insert into can_conduct (lab_name, type_id) values ('West-ward Pharmaceutical Corp.', '0641-0948');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', '35356-752');
insert into can_conduct (lab_name, type_id) values ('Arbonne International, LLC', '42508-139');
insert into can_conduct (lab_name, type_id) values ('Mondelez Global LLC', '12546-313');
insert into can_conduct (lab_name, type_id) values ('CALIFORNIA NATUREL', '61547-101');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-327');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-313');
insert into can_conduct (lab_name, type_id) values ('LEVEL ORAL CARE, LLC', '50001-121');
insert into can_conduct (lab_name, type_id) values ('Target Corporation', '11673-958');
insert into can_conduct (lab_name, type_id) values ('Bryant Ranch Prepack', '63629-3328');
insert into can_conduct (lab_name, type_id) values ('Noxell', '22700-128');
insert into can_conduct (lab_name, type_id) values ('Falcon Pharmaceuticals, Ltd.', '61314-645');
insert into can_conduct (lab_name, type_id) values ('Merck Sharp & Dohme Corp.', '0085-1287');
insert into can_conduct (lab_name, type_id) values ('Sun Pharma Global FZE', '47335-859');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-7671');
insert into can_conduct (lab_name, type_id) values ('Unit Dose Services', '50436-6051');
insert into can_conduct (lab_name, type_id) values ('Reckitt Benckiser, LLC', '63824-343');
insert into can_conduct (lab_name, type_id) values ('Boca Pharmacal, LLC', '64376-821');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-6101');
insert into can_conduct (lab_name, type_id) values ('AMI Cosmetic Co.,Ltd.', '59535-7901');
insert into can_conduct (lab_name, type_id) values ('Nature''s Innovation, Inc.', '10893-600');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '37205-320');
insert into can_conduct (lab_name, type_id) values ('Cadila Healthcare Limited', '65841-751');
insert into can_conduct (lab_name, type_id) values ('Amarin Pharma Inc.', '52937-001');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-440');
insert into can_conduct (lab_name, type_id) values ('Cape Medical Supply, Inc', '64932-1234');
insert into can_conduct (lab_name, type_id) values ('Teva Pharmaceuticals USA Inc', '0093-5786');
insert into can_conduct (lab_name, type_id) values ('Washington Homeopathic Products', '68428-042');
insert into can_conduct (lab_name, type_id) values ('AstraZeneca LP', '0186-0702');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2260');
insert into can_conduct (lab_name, type_id) values ('H E B', '37808-922');
insert into can_conduct (lab_name, type_id) values ('Lupin Pharmaceuticals, Inc.', '68180-323');
insert into can_conduct (lab_name, type_id) values ('SJ Creations, Inc.', '43269-638');
insert into can_conduct (lab_name, type_id) values ('King Bio Inc.', '57955-7302');
insert into can_conduct (lab_name, type_id) values ('KC Pharmaceuticals, Inc.', '55651-005');
insert into can_conduct (lab_name, type_id) values ('Qualitest Pharmaceuticals', '0603-6135');
insert into can_conduct (lab_name, type_id) values ('Rite Aid Corporation', '11822-0977');
insert into can_conduct (lab_name, type_id) values ('Sam''s West Inc', '68196-553');
insert into can_conduct (lab_name, type_id) values ('Sagent Pharmaceuticals', '25021-301');
insert into can_conduct (lab_name, type_id) values ('Ingles Market Inc', '62936-0042');
insert into can_conduct (lab_name, type_id) values ('Wal-Mart Stores Inc', '49035-124');
insert into can_conduct (lab_name, type_id) values ('Kareway Product, Inc.', '67510-0160');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-2371');
insert into can_conduct (lab_name, type_id) values ('Procter & Gamble Manufacturing Company', '37000-249');
insert into can_conduct (lab_name, type_id) values ('Fenwal Inc', '0942-0641');
insert into can_conduct (lab_name, type_id) values ('CVS Pharmacy', '59779-041');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1558');
insert into can_conduct (lab_name, type_id) values ('Lake Erie Medical DBA Quality Care Products LLC', '49999-050');
insert into can_conduct (lab_name, type_id) values ('BioActive Nutritional, Inc.', '43857-0287');
insert into can_conduct (lab_name, type_id) values ('Tiger Balm (Malaysia) Sdn. Bhd.', '66403-315');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1841');
insert into can_conduct (lab_name, type_id) values ('Remedy Makers', '10191-1248');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-0054');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-9420');
insert into can_conduct (lab_name, type_id) values ('AMOREPACIFIC', '43419-301');
insert into can_conduct (lab_name, type_id) values ('Actavis Inc.', '45963-342');
insert into can_conduct (lab_name, type_id) values ('Direct RX', '61919-147');
insert into can_conduct (lab_name, type_id) values ('Sandoz Inc', '0781-3003');
insert into can_conduct (lab_name, type_id) values ('Bare Escentuals Beauty, Inc.', '98132-720');
insert into can_conduct (lab_name, type_id) values ('Prime Packaging, Inc.', '13630-0042');
insert into can_conduct (lab_name, type_id) values ('Jubilant HollisterStier LLC', '65044-4857');
insert into can_conduct (lab_name, type_id) values ('Baxter Healthcare Corporation', '0338-0511');
insert into can_conduct (lab_name, type_id) values ('Mylan Institutional Inc.', '51079-953');
insert into can_conduct (lab_name, type_id) values ('ENCHANTE ACCESSORIES INC.', '50563-132');
insert into can_conduct (lab_name, type_id) values ('Preferred Pharmaceuticals, Inc.', '68788-8999');
insert into can_conduct (lab_name, type_id) values ('WALGREEN CO.', '0363-0583');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-416');
insert into can_conduct (lab_name, type_id) values ('Advanced Beauty Systems, Inc.', '51345-099');
insert into can_conduct (lab_name, type_id) values ('Allergy Laboratories, Inc.', '54575-319');
insert into can_conduct (lab_name, type_id) values ('Cardinal Health', '55154-4780');
insert into can_conduct (lab_name, type_id) values ('B. Braun Medical Inc.', '0264-7802');
insert into can_conduct (lab_name, type_id) values ('Antigen Laboratories, Inc.', '49288-0760');
insert into can_conduct (lab_name, type_id) values ('Mission Hills, S.A. de C.V.', '65954-007');
insert into can_conduct (lab_name, type_id) values ('Burkhart Dental Supply Inc', '43498-102');
insert into can_conduct (lab_name, type_id) values ('PD-Rx Pharmaceuticals, Inc.', '55289-626');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-1357');
insert into can_conduct (lab_name, type_id) values ('Reckitt Benckiser LLC', '63824-345');
insert into can_conduct (lab_name, type_id) values ('Jets, Sets, & Elephants Beauty Corp.', '50988-216');
insert into can_conduct (lab_name, type_id) values ('King Bio Inc.', '57955-0212');
insert into can_conduct (lab_name, type_id) values ('Air Liquide Healthcare America Corporation', '64735-010');
insert into can_conduct (lab_name, type_id) values ('ALK-Abello, Inc.', '0268-6601');
insert into can_conduct (lab_name, type_id) values ('SHISEIDO AMERICA INC.', '52686-343');
insert into can_conduct (lab_name, type_id) values ('Forces of Nature', '51393-7566');
insert into can_conduct (lab_name, type_id) values ('Ferring Pharmaceuticals Inc.', '55566-1501');
insert into can_conduct (lab_name, type_id) values ('REMEDYREPACK INC.', '49349-186');
insert into can_conduct (lab_name, type_id) values ('Crossing Cultures, LLC dba Goddess Garden', '58479-004');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-0274');
insert into can_conduct (lab_name, type_id) values ('China Ningbo Shangge Cosmetic Technology Corp.', '58503-022');
insert into can_conduct (lab_name, type_id) values ('Bryant Ranch Prepack', '63629-3201');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-1263');
insert into can_conduct (lab_name, type_id) values ('Stiefel Laboratories Inc', '63032-031');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-2075');
insert into can_conduct (lab_name, type_id) values ('Sun Pharmaceutical Industries Limited', '62756-402');
insert into can_conduct (lab_name, type_id) values ('Jubilant HollisterStier LLC', '65044-1020');
insert into can_conduct (lab_name, type_id) values ('Nelco Laboratories, Inc.', '36987-2340');
insert into can_conduct (lab_name, type_id) values ('Apotheca Company', '57520-0218');
insert into can_conduct (lab_name, type_id) values ('APP Pharmaceuticals, LLC', '63323-309');
insert into can_conduct (lab_name, type_id) values ('PSS World Medical', '68345-874');
insert into can_conduct (lab_name, type_id) values ('Fred''s Inc', '55315-163');
insert into can_conduct (lab_name, type_id) values ('Lornamead', '62721-0470');
insert into can_conduct (lab_name, type_id) values ('Kroger', '30142-154');
insert into can_conduct (lab_name, type_id) values ('Mutual Pharmaceutical Company, Inc.', '53489-281');
insert into can_conduct (lab_name, type_id) values ('Church & Dwight Co., Inc.', '10237-735');
insert into can_conduct (lab_name, type_id) values ('Wockhardt USA LLC.', '64679-993');
insert into can_conduct (lab_name, type_id) values ('Aurolife Pharma LLC', '13107-044');
insert into can_conduct (lab_name, type_id) values ('Mylan Pharmaceuticals Inc.', '0378-2146');
insert into can_conduct (lab_name, type_id) values ('PUR MINERALS', '67345-0691');
insert into can_conduct (lab_name, type_id) values ('Reckitt Benckiser LLC', '63824-112');
insert into can_conduct (lab_name, type_id) values ('STAT RX USA LLC', '16590-349');
insert into can_conduct (lab_name, type_id) values ('Mission Pharmacal Company', '0178-0620');
insert into can_conduct (lab_name, type_id) values ('Apotex Corp', '60505-0265');
